from typing import TypedDict, List, Optional
class AgentState(TypedDict):
    issue: str 
    repo_files: List[str] 
    relevant_files: List[str]
    repo_path: str 
    plan: str   # The agent's plan for addressing the issue
    patch: str  # The code changes generated by the agent
    tests: str  # The tests generated by the agent to validate the patch
    pr_url: Optional[str]  # The URL of the pull request created by the agent
    github_repo: str
    github_token: str 
    error: Optional[str]
    code_context: str
