import os
import re
from github import Github, GithubException
from backend.core.config import settings

def pr_opener(state: dict) -> dict:
    """
    AGENT 05 — PR Opener
 
    What it does:
    1. Connects to GitHub using the token
    2. Creates a new branch named after the issue
    3. Commits the patch files to that branch
    4. Opens a Pull Request with the plan as the description
    5. Returns: pr_url
 
    If no GitHub token is configured, it skips and returns a note instead.
    """
    patch = state["patch"]
    tests = state["tests"]
    plan = state["plan"]
    issue = state["issue"]
    github_repo = state.get("github_repo", settings.GITHUB_REPO)
    github_token = state.get("github_token", settings.GITHUB_TOKEN)

    #Skip PR creation if no token or repo is configured,so that the rest of the pipeline to run without errors.
    if not github_token or not github_repo:
        return {
            "pr_url": None,
            "error": "GitHub token or repo not configured. Skipping PR creation."
        }
 
    try:
        gh = Github(github_token)
        repo = gh.get_repo(github_repo)

        branch_name = _make_branch_name(issue)
 
        default_branch = repo.default_branch
        source = repo.get_branch(default_branch)
 
        # create the new branch
        repo.create_git_ref(
            ref=f"refs/heads/{branch_name}",
            sha=source.commit.sha
        )
 
        # commit the patch files to the branch
        _commit_files(repo, branch_name, patch, tests)
 
        # open the Pull Request
        pr_title = f"fix: {issue[:60]}" if len(issue) > 60 else f"fix: {issue}"
        pr_body = _build_pr_body(issue, plan, tests)
 
        pr = repo.create_pull(
            title=pr_title,
            body=pr_body,
            head=branch_name,
            base=default_branch,
        )
 
        return {"pr_url": pr.html_url}
 
    except GithubException as e:
        return {
            "pr_url": None,
            "error": f"GitHub API error: {e.data.get('message', str(e))}"
        }
    except Exception as e:
        return {
            "pr_url": None,
            "error": f"PR creation failed: {str(e)}"
        }
 
def _make_branch_name(issue: str) -> str:
    """Turns issue text into a valid git branch name."""
    slug = issue.lower()[:50]
    slug = re.sub(r"[^a-z0-9\s-]", "", slug)
    slug = re.sub(r"\s+", "-", slug.strip())
    slug = re.sub(r"-+", "-", slug)
    return f"autopr/{slug}"
 
 
def _commit_files(repo, branch_name: str, patch: str, tests: str):
    """
    Parses the patch output and commits each file to the branch.
    Patch format expected: lines starting with '# FILE: <path>' as separators.
    """
    files_to_commit = _parse_patch_files(patch)
    files_to_commit.update(_parse_patch_files(tests))
 
    for file_path, content in files_to_commit.items():
        try:
            existing = repo.get_contents(file_path, ref=branch_name)
            repo.update_file(
                path=file_path,
                message=f"fix: update {file_path}",
                content=content,
                sha=existing.sha,
                branch=branch_name,
            )
        except GithubException:
            repo.create_file(
                path=file_path,
                message=f"fix: add {file_path}",
                content=content,
                branch=branch_name,
            )
 
def _parse_patch_files(text: str) -> dict:
    result = {}
    current_file = None
    current_lines = []
 
    for line in text.splitlines():
        if line.startswith("# FILE:"):
            if current_file:
                result[current_file] = "\n".join(current_lines).strip()
            current_file = line.replace("# FILE:", "").strip()
            current_lines = []
        else:
            current_lines.append(line)
 
    if current_file:
        result[current_file] = "\n".join(current_lines).strip()
 
    return result
 
 
def _build_pr_body(issue: str, plan: str, tests: str) -> str:
    return f"""## Issue
{issue}
 
## Fix Plan
{plan}
 
## Tests Added
```python
{tests[:1000]}
```
 
---
*This PR was automatically generated by AutoPR 🤖*
"""
